---
title: "Model"
author: "Britney"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages, echo=FALSE}
library(tidyr) 
library(tidyverse)
library(dplyr) 
library(leaps)
library(MASS)
```

```{r, echo=FALSE}
setwd('/Users/britney/Desktop/STA 395/video-game-reviews/clean_data')
games = read.csv("clean_data_all.csv")
```

## Best subset

```{r, echo=FALSE}
models = regsubsets(user_score~., data = games, nvmax = 10)
summary(models)
#Vector memory exhausted
res.sum = summary(models)
data.frame(Adj.R2 = which.max(res.sum$adjr2))

trial = lm(user_score ~ platform + developers + meta_score + best_game + num_players + esrb_ratings + company + genres_Action, data = games)
summary(trial)

trial_company = lm(user_score ~ company, data = games)
summary (trial_company)

#Nintendo ***, PC **, Sega ***, Sony ***
trial_developers = lm(user_score ~ developers, data = games)
summary (trial_developers)

#K-A **
trial_esrb_ratings = lm(user_score ~ esrb_ratings, data = games)
summary (trial_esrb_ratings)

#meta_score ***
trial_meta_score = lm(user_score ~ meta_score, data = games)
summary (trial_meta_score)

#best_game ***
trial_best_game = lm(user_score ~ best_game, data = games)
summary (trial_best_game)

#multi_player *
trial_allow_multiplayer = lm(user_score ~ allow_multiplayer, data = games)
summary (trial_allow_multiplayer)

#online play (negative) ***
trial_allow_online = lm(user_score ~ allow_online, data = games)
summary (trial_allow_online)

full.model = lm(user_score ~ allow_online + allow_multiplayer + best_game + meta_score + company + genres_Action, most_shared, data = games)
summary(full.model)

step.model = stepAIC(full.model, direction = "both", 
                      trace = FALSE)
summary(step.model)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
